[package]
name = "test-rpc"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "local"
path = "rust/local_client/local.rs"

[dependencies]
chrono = "0.4.37"
